version: "3.3"

services:

  ui:
    build:
      context: ./ui
    ports:
      - "80:80"
    depends_on:
      - api-backend
      - celery-worker

  api-backend:
    build:
      context: ./web_api
    environment:
      - BROKER_URL=amqp://rabbit-server:5672
      - BACKEND_URL=redis://redis-server:6379
      - C_FORCE_ROOT="true"
    ports:
      - "5000:80"
    depends_on:
      - celery-worker

  celery-worker:
    build:
      context: ./worker
    environment:
      - BROKER_URL=amqp://rabbit-server:5672
      - BACKEND_URL=redis://redis-server:6379
      - C_FORCE_ROOT="true"
    depends_on:
      - redis-server
      - rabbit-server

  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbit-server:
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  flower:
    image: mher/flower:0.9.5
    command: ["flower", "--broker=amqp://guest@rabbit-server:5672", "--port=5555"]
    ports:
        - "5555:5555"
    depends_on:
        - rabbit-server
